//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.ApplicationDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int KindsId { get; set; }
        public double Quantity { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public decimal Price { get; set; }
    
        public virtual Kind Kind { get; set; }
    }
}
